apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: oes
    cluster: sapor-gate
  name: sapor-gate
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: oes
      cluster: sapor-gate
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oes
        cluster: sapor-gate
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=100.0
        - name: SPRING_PROFILES_ACTIVE
          value: overrides,local
        image: quay.io/opsmxpublic/ubi8-spin-gate:1.20.0
        imagePullPolicy: IfNotPresent
        lifecycle: {}
        name: gate
        ports:
        - containerPort: 8084
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8084
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 650Mi
          requests:
            cpu: 300m
            memory: 650Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: sapor-gate-files
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: sapor-gate-files
        secret:
          defaultMode: 420
          secretName: sapor-gate-files
